spring:
  application:
    name: providerTest
  output:
    ansi:
      enabled: always # permite ver el log como colores
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:gestion_fitpower;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password: admin
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8090

logging:
  level:
    root: info
